-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigserial NOT NULL,
    username character varying(225) NOT NULL,
    email character varying NOT NULL,
    password_hash text NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    date_created timestamp without time zone NOT NULL DEFAULT current_timestamp,
    weight integer NOT NULL,
    CONSTRAINT pk_users_user_id PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE public.users
    IS 'for users';

CREATE TABLE IF NOT EXISTS public.workouts
(
    workout_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    workout_date timestamp without time zone NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    duration_minutes integer,
    notes text,
    CONSTRAINT pk_workout_id PRIMARY KEY (workout_id)
);

COMMENT ON TABLE public.workouts
    IS 'This table will store information about each workout session a user completes.';

CREATE TABLE IF NOT EXISTS public.workout_exercises
(
    workout_exercise_id bigserial NOT NULL,
    workout_id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    set_number integer NOT NULL,
    repetitions integer NOT NULL,
    weight integer,
    unit text,
    duration_seconds integer,
    distance integer,
    distance_unit character varying(10),
    notes text,
    CONSTRAINT pk_workout_exercise_id PRIMARY KEY (workout_exercise_id)
);

COMMENT ON TABLE public.workout_exercises
    IS 'for workout excersises';

CREATE TABLE IF NOT EXISTS public.exercises
(
    exercise_id bigserial NOT NULL,
    exercise_name character varying(225) NOT NULL,
    description text,
    muscle_group text,
    exercise_type text,
    CONSTRAINT pk_exercise_id PRIMARY KEY (exercise_id),
    CONSTRAINT uq_exercise_name UNIQUE (exercise_name)
);

COMMENT ON TABLE public.exercises
    IS 'This table will store a list of all possible exercises users can perform. ';

ALTER TABLE IF EXISTS public.workouts
    ADD CONSTRAINT fk_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.workout_exercises
    ADD CONSTRAINT fk_workoutexercises_workout_id FOREIGN KEY (workout_id)
    REFERENCES public.workouts (workout_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.workout_exercises
    ADD CONSTRAINT fk_workoutexercises_exercise_id FOREIGN KEY (exercise_id)
    REFERENCES public.exercises (exercise_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;